# This file is part of JavaSMT,
# an API wrapper for a collection of SMT solvers:
# https://github.com/sosy-lab/java-smt
#
# SPDX-FileCopyrightText: 2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

version: build {build} {branch}

os: Visual Studio 2019

clone_depth: 1

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\ant\apache-ant-1.10.8" )) {
        (new-object System.Net.WebClient).DownloadFile(
        'https://archive.apache.org/dist/ant/binaries/apache-ant-1.10.8-bin.zip',
          'C:\ant-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\ant-bin.zip", "C:\ant")
      }
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk14
  - cmd: SET PATH=C:\ant\apache-ant-1.10.8\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET IVY_CACHE_DIR=C:\ivy
  - cmd: echo %USERPROFILE%
  - cmd: echo %PATH%
  - cmd: java -version

build_script:
  - ant build

test_script:
  - ant unit-tests

on_finish:
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $files = Get-ChildItem -Path ".\junit\TEST-*.xml" -Exclude "*VariableNames*"
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      foreach($file in $files){
        echo $file.FullName
        $wc.UploadFile($url, $file.FullName)
      }
  - ps: |
      $files = Get-ChildItem -Path ".\hs_err_pid*"
      foreach($file in $files){
        echo $file.FullName
        Push-AppveyorArtifact $file.FullName -DeploymentName $file.name
      }
  - ps: |
      $files = Get-ChildItem -Path ".\replay_pid*"
      foreach($file in $files){
        echo $file.FullName
        Push-AppveyorArtifact $file.FullName -DeploymentName $file.name
      }
  - ps: |
      7z a JUnit.html.zip JUnit.html
      Push-AppveyorArtifact JUnit.html.zip -DeploymentName "JUnit Report"

cache:
  - C:\ant
  - C:\ivy

notifications:
  - provider: Email
    to:
      - java-smt-dev@googlegroups.com
    on_build_success: false
    on_build_status_changed: true
