language: java
jdk:
  - oraclejdk8
env:
  global:
  - GH_REF: github.com/dbeyer/java-smt.git
  - CMD=""
  - CMD2=""
  matrix:
  - NAME=FindBugs      DEPLOY=false CMD="ant run-findbugs -Dfindbugs.output=text && cat FindBugs.xml && test \! -s FindBugs.xml"
  - NAME=Checkstyle    DEPLOY=false CMD="ant run-checkstyle -Dcheckstyle.output=plain && cat Checkstyle*.xml && [ $(cat Checkstyle*.xml | grep -vic audit) -eq 0 ]"
  - NAME=format-source DEPLOY=false CMD="ant format-source && git diff -s --exit-code"
  - NAME=ECJ           DEPLOY=false CMD="ant build-project-ecj"
  - NAME=Build         DEPLOY=false CMD="ant build-project"
  - NAME=Coverage      DEPLOY=true  CMD="ant unit-tests-coverage" CMD2="ant javadoc"

install:
  - ant resolve-dependencies -Divy.repo.url=http://www.sosy-lab.org/ivy
addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - $CMD
  - $CMD2
deploy:
  - skip_cleanup: true
    provider: script
    script: DEPLOY && build/deploy-gh-pages.sh
  - skip_cleanup: true
    provider: script
    script: DEPLOY && build/deploy-coverage.sh
notifications:
  email:
  - java-smt-dev@googlegroups.com
git:
  depth: 1
cache:
  directories:
  - $HOME/.ivy2
