language: java
install:
  - ant resolve-dependencies
script:
  - ant unit-tests
  - ant run-findbugs -Dfindbugs.output=text && cat FindBugs.xml && test \! -s FindBugs.xml
notifications:
  email:
  - java-smt-dev@googlegroups.com
cache:
  directories:
  - $HOME/.ivy2
