language: java
# Only for newer ant, containers on Travis only have ant 1.8.2 which fails
sudo: required
dist: trusty
jdk:
  - oraclejdk8
env:
  global:
  - GH_REF: github.com/dbeyer/java-smt.git
install:
  - ant resolve-dependencies -Divy.repo.url=http://www.sosy-lab.org/ivy
matrix:
  include:
    - script:
        - ant run-findbugs -Dfindbugs.output=text && cat FindBugs.xml && test \! -s FindBugs.xml
      jdk: oraclejdk8
      env: NAME=FindBugs
    - script:
        - ant run-checkstyle -Dcheckstyle.output=plain && cat Checkstyle*.xml && [ $(cat Checkstyle*.xml | grep -vic audit) -eq 0 ]
      jdk: oraclejdk8
      env: NAME=Checkstyle
    - script:
        - ant javadoc
      jdk: oraclejdk8
      env: NAME=Javadoc
    - script:
        - ant format-source && git diff -s --exit-code
      jdk: oraclejdk8
      env: NAME=format-source

script:
  - ant build-project-ecj
  - ant clean unit-tests-coverage
deploy:
  - skip_cleanup: true
    provider: script
    script: build/deploy-gh-pages.sh
  - skip_cleanup: true
    provider: script
    script: build/deploy-coverage.sh
notifications:
  email:
  - java-smt-dev@googlegroups.com
git:
  depth: 1
cache:
  directories:
  - $HOME/.ivy2
