language: java
jdk:
  - oraclejdk8
env:
  global:
  - GH_REF: github.com/dbeyer/java-smt.git
  - NAME: Build and Deploy
install:
  - ant resolve-dependencies -Divy.repo.url=http://www.sosy-lab.org/ivy
addons:
  apt:
    packages:
      - oracle-java8-installer
matrix:
  include:
    - script:
        - ant run-findbugs -Dfindbugs.output=text && cat FindBugs.xml && test \! -s FindBugs.xml
      jdk: oraclejdk8
      env: NAME=FindBugs
    - script:
        - ant run-checkstyle -Dcheckstyle.output=plain && cat Checkstyle*.xml && [ $(cat Checkstyle*.xml | grep -vic audit) -eq 0 ]
      jdk: oraclejdk8
      env: NAME=Checkstyle
    - script:
        - ant format-source && git diff -s --exit-code
      jdk: oraclejdk8
      env: NAME=format-source
    - script:
        - ant build-project-ecj
      jdk: oraclejdk8
      env: NAME=ECJ
script:
  - ant build-project
  - ant clean unit-tests-coverage
  - ant javadoc
deploy:
  - skip_cleanup: true
    provider: script
    script: build/deploy-gh-pages.sh
  - skip_cleanup: true
    provider: script
    script: build/deploy-coverage.sh
notifications:
  email:
  - java-smt-dev@googlegroups.com
git:
  depth: 1
cache:
  directories:
  - $HOME/.ivy2
