language: java
jdk:
  - oraclejdk8
env:
  global:
  - GH_REF: github.com/dbeyer/java-smt.git
install:
  - ant resolve-dependencies -Divy.repo.url=http://www.sosy-lab.org/ivy
addons:
  apt:
    packages:
      - oracle-java8-installer
matrix:
  include:
    - script:
        - ant run-findbugs -Dfindbugs.output=text && cat FindBugs.xml && test \! -s FindBugs.xml
      jdk: oraclejdk8
      env: NAME=FindBugs
    - script:
        - ant run-checkstyle -Dcheckstyle.output=plain && cat Checkstyle*.xml && [ $(cat Checkstyle*.xml | grep -vic audit) -eq 0 ]
      jdk: oraclejdk8
      env: NAME=Checkstyle
    - script:
        - ant format-source && git diff -s --exit-code
      jdk: oraclejdk8
      env: NAME=format-source
    - script:
        - ant build-project-ecj
      jdk: oraclejdk8
      env: NAME='Build ECJ'
    - script:
        - ant build-project
      jdk: oraclejdk8
      env: NAME=Build
    - script:
        - ant unit-tests-coverage
        - ant javadoc
      jdk: oraclejdk8
      env: NAME='Testing and Javadoc' DEPLOY=true
script:
  - true # overrides default script from Travis
deploy:
  - skip_cleanup: true
    provider: script
    script: build/deploy-gh-pages.sh
    on:
      branch: master
      condition: "$DEPLOY" = true
  - skip_cleanup: true
    provider: script
    script: build/deploy-coverage.sh
    on:
      branch: master
      condition: "$DEPLOY" = true
notifications:
  email:
  - java-smt-dev@googlegroups.com
git:
  depth: 1
cache:
  directories:
  - $HOME/.ivy2
